FROM node:alpine as builder

WORKDIR /app

COPY ./package.json ./yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build


FROM nginx

COPY ./default.conf /etc/nginx/conf.d/

COPY --from=builder /app/build /usr/share/nginx/html